version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - frontend
      - backend

  react:
    image: your_dockerhub_username/front:latest
    networks:
      - frontend
      - backend
    deploy:
      replicas: 3
    volumes:
      - ./client:/app
      - /app/node_modules

  api:
    image: your_dockerhub_username/back:latest
    networks:
      - backend
    deploy:
      replicas: 1
    volumes:
      - ./server:/app
      - /app/node_modules

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=signup
    ports:
      - '3306:3306'
    volumes:
      - ./myss.sql:/docker-entrypoint-initdb.d/myss.sql
    networks:
      - backend

networks:
  frontend:
  backend:

