version: '3.8'

services:
  react:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5900:5173'
    networks:
      - commonn

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - db
    networks:
      - commonn

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=signup
    ports:
      - '3306:3306'
    networks:
      - commonn

networks:
  commonn: {}
