version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react
      - api
    networks:
      - commonn

  react:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - commonn
    ports:
      - '5900:5173'

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - db
    networks:
      - commonn

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=signup
    ports:
      - '3306:3306'
    volumes:
      - ./myss.sql:/docker-entrypoint-initdb.d/myss.sql
    networks:
      - commonn

networks:
  commonn: {}

